
[pre-commit]
parallel = true

[pre-commit.commands.lint]
run = "pnpm ci:lint"

[pre-commit.commands.fix]
run = "pnpm fix"

[pre-commit.commands.format]
run = "pnpm ci:format"

[commit-msg.scripts."commitlint.sh"]
runner = "bash"
