packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@astrojs/check": ^0.9.3
  "@astrojs/language-server": ^2.14.2
  "@astrojs/mdx": ^3.1.7
  "@astrojs/react": ^3.6.2
  "@astrojs/rss": ^4.0.7
  "@astrojs/sitemap": ^3.1.6
  "@astrojs/tailwind": ^5.1.1
  "@biomejs/biome": ^1.5.3
  "@commitlint/cli": 17.7.1
  "@commitlint/config-conventional": 17.7.0
  "@expressive-code/plugin-line-numbers": ^0.35.3
  "@fontsource-variable/onest": ^5.0.3
  "@fontsource/bellota": ^5.0.12
  "@fontsource/monaspace-neon": ^5.1.0
  "@iconify-json/iconoir": ^1.1.42
  "@iconify-json/ph": ^1.1.11
  "@iconify-json/tabler": ^1.2.5
  "@manypkg/cli": 0.21.0
  "@nextui-org/button": 2.0.9
  "@radix-ui/react-avatar": 1.0.3
  "@radix-ui/react-hover-card": 1.0.6
  "@radix-ui/react-separator": 1.0.3
  "@radix-ui/react-slot": ^1.0.2
  "@rollup/plugin-typescript": 11.1.2
  "@swc-node/register": 1.6.6
  "@swc/core": 1.3.76
  "@swc/helpers": 0.5.1
  "@types/mdx": 2.0.6
  "@types/node": 18.15.11
  "@types/react": 18.0.33
  "@types/react-dom": ^18.2.23
  "@unpic/astro": ^0.0.47
  astro: ^4.15.8
  astro-expressive-code: ^0.35.3
  astro-icon: ^1.1.0
  autoprefixer: 10.4.14
  class-variance-authority: 0.6.1
  clsx: 1.2.1
  date-fns: ^4.1.0
  fdir: 6.0.2
  framer-motion: 10.12.17
  fumadocs-twoslash: ^1.0.1
  fumadocs-ui: ^8.1.1
  iconoir-react: ^7.4.0
  lefthook: ^1.6.1
  lucide-react: 0.248.0
  mdast-util-to-string: ^4.0.0
  next: 14.1.0
  next-themes: ^0.2.1
  postcss: 8.4.31
  prettier: ^3.3.2
  prettier-plugin-astro: ^0.14.0
  react: 18.2.0
  react-dom: 18.2.0
  react-icons: 4.10.1
  reading-time: ^1.5.0
  rehype-accessible-emojis: 0.3.2
  remark-gemoji: 7.0.1
  sharp: 0.32.6
  sharp-ico: ^0.1.5
  tailwind-merge: 1.13.2
  tailwind-variants: 0.1.13
  tailwindcss-animate: 1.0.6
  ts-node: 10.9.1
  tslib: 2.6.1
  turbo: 2.1.3
  typewriter-effect: 2.20.1
  zod: 3.23.8
