packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  backend:
    '@expressive-code/plugin-line-numbers': ^0.41.5
  build:
    '@rollup/plugin-typescript': 12.3.0
    '@tailwindcss/vite': ^4.1.18
    rollup-preserve-directives: ^1.1.3
  cli:
    taze: ^19.9.2
  dev:
    '@astrojs/language-server': ^2.16.2
    '@react-pdf/renderer': ^4.3.1
    '@swc-node/register': ^1.11.1
    '@swc/core': ^1.15.7
    '@swc/helpers': ^0.5.17
    '@tweakpane/core': ^2.0.5
    fdir: 6.5.0
    lefthook: ^2.0.12
    react-compiler-runtime: 19.0.0-beta-af1b7da-20250417
    ts-node: 10.9.2
    tslib: 2.8.1
    typescript: 5.9.3
  frontend:
    '@react-three/drei': ^10.7.7
    '@react-three/fiber': ^9.4.2
    '@react-three/rapier': ^2.2.0
    three: ^0.182.0
  icons:
    '@iconify-json/iconoir': ^1.2.10
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/material-icon-theme': ^1.2.44
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/octicon': ^1.2.19
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/simple-icons': ^1.2.63
    '@iconify-json/tabler': ^1.2.24
    '@iconify-json/vscode-icons': ^1.2.37
    astro-icon: 1.1.5
    iconoir-react: ^7.11.0
    lucide-react: 0.562.0
    react-icons: 5.5.0
  lint:
    '@biomejs/biome': ^2.3.10
    '@commitlint/cli': 20.2.0
    '@commitlint/config-conventional': 20.2.0
    prettier: ^3.7.4
    prettier-plugin-astro: 0.14.1
  monorepo:
    turbo: 2.7.0
  prod:
    '@astrojs/check': ^0.9.6
    '@astrojs/mdx': ^4.3.13
    '@astrojs/react': ^4.4.2
    '@astrojs/rss': ^4.0.14
    '@astrojs/sitemap': ^3.6.0
    '@fontsource-variable/onest': ^5.2.11
    '@fontsource/bellota': ^5.2.7
    '@fontsource/maple-mono': ^5.2.6
    '@fontsource/monaspace-neon': ^5.2.5
    '@nextui-org/button': 2.2.9
    '@radix-ui/react-avatar': 1.1.11
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-scroll-area': ^1.2.10
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-tooltip': ^1.2.8
    '@signpdf/placeholder-plain': ^3.2.5
    '@signpdf/signer-p12': ^3.2.4
    '@signpdf/signpdf': ^3.2.5
    '@unpic/placeholder': ^0.1.2
    astro: ^5.16.6
    blurhash: ^2.0.5
    date-fns: ^4.1.0
    framer-motion: 12.23.26
    fumadocs-core: ^16.3.1
    fumadocs-twoslash: ^3.1.10
    fumadocs-ui: ^16.3.1
    gsap: ^3.14.2
    lightningcss: ^1.30.2
    mdast-util-to-string: ^4.0.0
    meshline: ^3.3.1
    node-forge: ^1.3.3
    pdf-lib: ^1.17.1
    random: ^5.4.1
    react: ^19.1.4
    react-dom: ^19.1.4
    react-tweakpane: ^0.8.1
    reading-time: ^1.5.0
    rehype-accessible-emojis: 0.3.2
    rehype-katex: ^7.0.1
    remark-gemoji: 8.0.0
    remark-math: ^6.0.0
    sharp: 0.34.5
    sharp-ico: ^0.1.5
    simplex-noise: ^4.0.3
    tailwind-variants: 3.2.2
    tweakpane: ^4.0.5
    typewriter-effect: 2.22.0
  style:
    '@tailwindcss/postcss': ^4.1.18
    autoprefixer: 10.4.23
    postcss: 8.5.6
    tailwind-merge: 3.4.0
    tailwindcss: 4.1.18
    tailwindcss-animate: 1.0.7
  syntax:
    '@shikijs/twoslash': ^3.20.0
  types:
    '@types/mdx': 2.0.13
    '@types/node': 25.0.3
    '@types/node-forge': ^1.3.14
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@types/three': ^0.182.0
  utils:
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    zod: ^4.2.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - oxc-resolver
  - sharp
