packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@biomejs/biome': ^1.9.4
  '@commitlint/cli': 17.7.1
  '@commitlint/config-conventional': 17.7.0
  '@expressive-code/plugin-line-numbers': ^0.40.1
  '@fontsource-variable/onest': ^5.1.1
  '@fontsource/bellota': ^5.1.1
  '@fontsource/monaspace-neon': ^5.1.0
  '@iconify-json/iconoir': ^1.2.7
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/tabler': ^1.2.15
  '@nextui-org/button': 2.0.9
  '@radix-ui/react-avatar': 1.0.3
  '@radix-ui/react-hover-card': 1.0.6
  '@radix-ui/react-separator': 1.0.3
  '@radix-ui/react-slot': ^1.1.1
  '@rollup/plugin-typescript': 11.1.2
  '@swc-node/register': 1.6.6
  '@swc/core': 1.3.76
  '@swc/helpers': 0.5.1
  '@types/mdx': 2.0.6
  '@types/node': 18.15.11
  '@types/react': 18.0.33
  '@types/react-dom': ^19.0.3
  autoprefixer: 10.4.14
  class-variance-authority: 0.6.1
  clsx: 1.2.1
  date-fns: ^4.1.0
  fdir: 6.0.2
  framer-motion: 10.12.17
  iconoir-react: ^7.10.1
  lefthook: ^1.10.10
  lucide-react: 0.248.0
  mdast-util-to-string: ^4.0.0
  postcss: 8.4.31
  prettier: ^3.4.2
  react: 18.2.0
  react-dom: 18.2.0
  react-icons: 4.10.1
  reading-time: ^1.5.0
  rehype-accessible-emojis: 0.3.2
  remark-gemoji: 7.0.1
  sharp: 0.32.6
  sharp-ico: ^0.1.5
  tailwind-merge: 1.13.2
  tailwind-variants: 0.1.13
  tailwindcss: 4.0.3
  tailwindcss-animate: 1.0.6
  ts-node: 10.9.1
  tslib: 2.6.1
  turbo: 2.4.0
  typescript: 5.6.3
  typewriter-effect: 2.20.1
  zod: 3.23.8
