packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/language-server": ^2.15.4
  "@astrojs/mdx": ^4.0.8
  "@astrojs/react": ^4.2.0
  "@astrojs/rss": ^4.0.11
  "@astrojs/sitemap": ^3.2.1
  "@biomejs/biome": ^1.9.4
  "@commitlint/cli": 17.7.1
  "@commitlint/config-conventional": 17.7.0
  "@expressive-code/plugin-line-numbers": ^0.40.1
  "@fontsource-variable/onest": ^5.1.1
  "@fontsource/bellota": ^5.1.1
  "@fontsource/monaspace-neon": ^5.1.0
  "@iconify-json/iconoir": ^1.2.7
  "@iconify-json/ph": ^1.2.2
  "@iconify-json/tabler": ^1.2.15
  "@nextui-org/button": 2.0.9
  "@radix-ui/react-avatar": 1.0.3
  "@radix-ui/react-hover-card": 1.0.6
  "@radix-ui/react-scroll-area": ^1.2.2
  "@radix-ui/react-separator": 1.0.3
  "@radix-ui/react-slot": ^1.1.1
  "@radix-ui/react-tooltip": ^1.1.7
  "@rollup/plugin-typescript": 11.1.2
  "@shikijs/twoslash": ^2.2.0
  "@swc-node/register": 1.6.6
  "@swc/core": 1.3.76
  "@swc/helpers": 0.5.1
  "@tailwindcss/postcss": ^4.0.3
  "@tailwindcss/vite": ^4.0.3
  "@types/mdx": 2.0.6
  "@types/node": 18.15.11
  "@types/react": 18.0.33
  "@types/react-dom": ^19.0.3
  "@unpic/placeholder": ^0.1.2
  astro: ^5.2.3
  astro-icon: 1.1.5
  autoprefixer: 10.4.14
  blurhash: ^2.0.5
  class-variance-authority: 0.6.1
  clsx: 1.2.1
  date-fns: ^4.1.0
  fdir: 6.0.2
  framer-motion: 10.12.17
  fumadocs-core: ^15.0.1
  fumadocs-twoslash: ^3.0.0
  fumadocs-ui: ^15.0.1
  iconoir-react: ^7.10.1
  lefthook: ^1.10.10
  lightningcss: ^1.29.1
  lucide-react: 0.248.0
  mdast-util-to-string: ^4.0.0
  postcss: 8.4.31
  prettier: ^3.4.2
  prettier-plugin-astro: 0.14.1
  react: 18.2.0
  react-compiler-runtime: 19.0.0-beta-55955c9-20241229
  react-dom: 18.2.0
  react-icons: 4.10.1
  reading-time: ^1.5.0
  rehype-accessible-emojis: 0.3.2
  remark-gemoji: 7.0.1
  rollup-preserve-directives: ^1.1.3
  sharp: 0.32.6
  sharp-ico: ^0.1.5
  tailwind-merge: 1.13.2
  tailwind-variants: 0.1.13
  tailwindcss: 4.0.3
  tailwindcss-animate: 1.0.6
  taze: ^18.3.0
  ts-node: 10.9.1
  tslib: 2.6.1
  turbo: 2.4.0
  typescript: 5.6.3
  typewriter-effect: 2.20.1
  zod: ^3.24.1
